version: '3.3'
services:

  rabbitmq-reporting:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq-reporting
    ports:
        - 5672:5672
        - 15672:15672
  
  reporting-api-db-service:
    image: postgis/postgis
    container_name: reporting-api-db-service
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432

  reporting-api:
    build: .
    container_name: reporting-api
    restart: always
    environment:
      MAINDB_ENDPOINT: reporting-api-db-service
      MAINDB_DBNAME: postgres
      MAINDB_USERNAME: postgres
      MAINDB_PASSWORD: password
      RABBITMQ_HOST: rabbitmq-reporting
    ports:
      - 8081:8081
    depends_on:
      - reporting-api-db-service
      - rabbitmq-reporting
#
#  tests:
#    image: maven:3
#    stop_signal: SIGKILL
#    stdin_open: true
#    tty: true
#    working_dir: $PWD
#    volumes:
#      - $PWD:$PWD
#      - /var/run/docker.sock:/var/run/docker.sock
      # Maven cache (optional)
#      - ~/.m2:/root/.m2
#    command: mvn test
 